library/books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.book_list),
    path('book/<int:book_id>/', views.book_info, name='book_info'),
]

library/library/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
]

library/books/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)
    birth_date = models.DateTimeField('birth date')
    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    date_published = models.DateTimeField('date published')
    def __str__(self):
        return f"{str(self.title), str(self.author)}"

library/books/views.py
from django.http import HttpResponse
from .models import Book
from django.template import loader
from django.shortcuts import render,get_object_or_404

def index(request):
    return HttpResponse("Library")

def book_info(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'books/detail.html', {'book' : book})

def book_list(request):
    latest_books_list = Book.objects.order_by('-date_published')[:5]
    context = {'latest_books_list' : latest_books_list}
    return render(request, 'books/index.html', context)

library/books/templates/books/detail.html
<h1>{{book.title}}</h1>
<h2>{{book.author}}</h2>
<h2>Published: {{book.date_published.year}}</h2>

library/books/templates/books/index.html
{% if latest_books_list %}
    <ul>
        {% for book in latest_books_list %}
            <h2><li><a href="{% url 'books:book_info' book.id %}">{{ book.author }}. {{ book.title }}</a></li></h2>
        {% endfor %}
    </ul>
{% else %}
    <p>No books are available.</p>
{% endif %}